spring:
  profiles:
    active:
      - prod
    include:
      - jwt
      - encryption

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(lvsfZVjGKrGfwhf6K9I64Tx7WIjMvGTDwEv3WR7HmSc4+2bTZ09YpnyCqXFfhsdsL0/6Pvo0GSakXicyoP4s+mWlXR320Rx+Ivf/A9T3OHt6c7/OMb6jgA==)
            client-secret: ENC(H/os4FOIOPMpDvmYqwmdoSZ+Rr7KhKNMMR+d8lVwoaTX2w7cmQYxd897tIaSDPmv)
            scope:
              - email
              - profile
            redirect-uri: ENC(jPzm5aVZK5YTjTstZbnchxHZU8XEs/+JYME82lO2RNACpo/5HpvIdZAi8zdiDkEsR7HGNSXPwFdzOAcxjcmf7g==)

          kakao:
            client-id: ENC(BuDvOtYmCk1LbabP42SKUsqjfH8HbYR/a9kun+TdCRFRpAKjWOMyVEQ5G/XfryKl)
            redirect-uri: ENC(iTA1gzu0Gbf1ISG0v7uj7/2NGtKKoHKo2WO9Nqs2p80DQrAjsYVV8/CAAB0nmecznrd7ySV+JomH5cnVW2aHiw==)
            authorization-grant-type: ENC(9nVPmWOsNxVZmjE86lq/qnfnKNJuiyRsgSWkvKMPAtc=)
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
    password: ${jasypt_encryptor_password}
