spring:
  profiles:
    active:
      - ${RUN_ENV}
    include:
      - jwt
      - env
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
    password: ${jasypt_encryptor_password}

