spring:
  profiles:
    active:
      - prod
    include:
      - jwt
      - encryption

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(DYrT/IAFmx5mTdSt5OtED+ljt7QFXYGDkBhQeDskxDQlIOKkIn6JgiPlpcaKBzRTg9VTYXVnX0q+xquxlxXseoSagVDvc8R/vKuygHSOnUMQockGxYlu8w==)
            client-secret: ENC(5dgsSyAUPMUolBTIqkW14WFTm/e2TJGHQSkikD9hSLMcQbc+eeQWKI1yoocYzHGm)
            scope:
              - email
              - profile
            redirect-uri: ENC(+IpZhB5MGa4Mf3ZJGJIY65kVWOi7LGRG5kFfxJyucj9TNUy5JEPmieUj7y2DWSNnijNx80WNiGc=)

          kakao:
            client-id: ENC(BuDvOtYmCk1LbabP42SKUsqjfH8HbYR/a9kun+TdCRFRpAKjWOMyVEQ5G/XfryKl)
            redirect-uri: ENC(SAEVudHVavQl7Y3+Z2/wDXlXHzOr8wL+05IioN7Tpz5saEqKLTf9Hig4EWViWb57jpiy5SR75Nw=)
            authorization-grant-type: ENC(9nVPmWOsNxVZmjE86lq/qnfnKNJuiyRsgSWkvKMPAtc=)
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
    password: ${jasypt_encryptor_password}
