name: quiz-module

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back-spring/jobseeckerstudio/quiz/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      jasypt_encryptor_password: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: jobseeckerstudio
      MYSQL_USER: ${{secrets.LOCAL_MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.LOCAL_MYSQL_PASSWORD}}
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up MYSQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'jobseeckerstudio'
          mysql user: ${{secrets.LOCAL_MYSQL_USER}}
          mysql password: ${{secrets.LOCAL_MYSQL_PASSWORD}}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/quiz
          mvn clean package
      - name: Test
        run: |
          cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/quiz
          mvn -B test
#       - name: Build Docker image
#         run: |
#           cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/quiz
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_QUIZ_SPRING_IMAGE_NAME }}:${{ github.sha }} \
#             --build-arg JASYPT_ENCRYPTOR_PASSWORD=${{secrets.JASYPT_ENCRYPTOR_PASSWORD}} \
#             --build-arg MYSQL_USER=${{secrets.MYSQL_USER}} \
#             --build-arg MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}} \
#             --build-arg MYSQL_HOST=${{secrets.MYSQL_HOST}} \
#             --build-arg MYSQL_PORT=${{secrets.MYSQL_PORT}} \
#             --build-arg MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}} \
#             --build-arg REDIS_HOST=${{secrets.REDIS_HOST}} \
#             --build-arg REDIS_PORT=${{secrets.REDIS_PORT}} \
#             .
#       - name: Push Docker image
#         run: |
#           docker images
#           docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_QUIZ_SPRING_IMAGE_NAME }}:${{ github.sha }}
