name: quiz-batch-module

on:
  push:
    branches: 
      - main
    paths:
      - 'spring-module/jobseeckerstudio/quiz-batch/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      env_run: test
      jasypt_encryptor_password: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: jobseeckerstudio
      MYSQL_USER: ${{secrets.LOCAL_MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.LOCAL_MYSQL_PASSWORD}}
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up MYSQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'jobseeckerstudio'
          mysql user: ${{secrets.LOCAL_MYSQL_USER}}
          mysql password: ${{secrets.LOCAL_MYSQL_PASSWORD}}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: QuizBatch Build with Maven 
        env:
          run_env: ${{ env.env_run }}
          jasypt_encryptor_password: ${{ env.jasypt_encryptor_password }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_PORT: ${{ env.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          REDIS_HOST: ${{ env.REDIS_HOST }}
          REDIS_PORT: ${{ env.REDIS_PORT }}
        run: |
          cd ../JobSeeckerStudio/spring-module/jobseeckerstudio/quiz-batch
          mvn clean package

