# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: user-module

on:
  push:
    branches: [ "main" ]
#     paths:
#       - 'back-spring/jobseeckerstudio/user/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      jasypt_encryptor_password: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: jobseeckerstudio
      MYSQL_USER: ${{secrets.LOCAL_MYSQL_USER}}
      MYSQL_PASSWORD: ${{secrets.LOCAL_MYSQL_PASSWORD}}
#     services:
#       mysql:
#         image: mysql:5.7
#         env:
#           MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
#           MYSQL_DATABASE: jobseeckerstudio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up MYSQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'jobseeckerstudio'
          mysql user: ${{secrets.LOCAL_MYSQL_USER}}
          mysql password: ${{secrets.LOCAL_MYSQL_PASSWORD}}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/user
          mvn clean package -Djasypt_encryptor_password=${{secrets.JASYPT_ENCRYPTOR_PASSWORD}} -DMYSQL_USER=${{secrets.LOCAL_MYSQL_USER}} -DMYSQL_PASSWORD=${{secrets.LOCAL_MYSQL_PASSWORD}} -DMYSQL_HOST=localhost -DMYSQL_PORT=3306 -DMYSQL_DATABASE=jobseeckerstudio
      - name: Run tests
        run: |
          cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/user
          mvn -B test
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: back-spring/jobseeckerstudio/user
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_USER_IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            MYSQL_PORT=${{ secrets.MYSQL_PORT }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      
