# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: userModuleTestCi

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      jasypt_encryptor_password: ${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
#       MYSQL_DATABASE: jobseeckerstudio
#       MYSQL_USER: root
#       MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
#     services:
#       mysql:
#         image: mysql:8.0
#         env:
#           MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
#           MYSQL_DATABASE: jobseeckerstudio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up MYSQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'jobseeckerstudio'
          mysql user: 'jobseeckerstudio'
          mysql password: ${{secrets.MYSQL_PASSWORD}}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/user
          mvn -B clean install
      - name: Run tests
        run: |
          cd ../JobSeeckerStudio/back-spirng/jobseeckerstudio/user
          mvn -B test
